name: Android Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Gradle Build Action
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-home-cache-cleanup: true
      - name: Build Debug APK
        run: ./gradlew assembleDebug


      - name: Upload a Build Artifact (APK)
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk